library(Rcmdr)
library(splines)
library(RcmdrMisc)
library(sandwich)
library(effects)
library(RcmdrPlugin.IPSUR)
data("RcmdrTestDrive")
View(RcmdrTestDrive)
x<-subset(RcmdrTestDrive, gender=="Male")
View(x)
mean(x$salary)
y<-subset(RcmdrTestDrive, gender=="Female")
View(y)
mean(y$salary)
sd(x$salary)
sd(y$salary)
mean(RcmdrTestDrive$salary)
